//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class billOfsale
    {
        public billOfsale()
        {
            this.items = new HashSet<item>();
        }
    
        public int SaleID { get; set; }
        public System.DateTime SaleDate { get; set; }
        public float SaleTotal { get; set; }
        public int SaleCountItem { get; set; }
    
        public virtual ICollection<item> items { get; set; }
    }
}
