//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public int item_id { get; set; }
        public string Item_name { get; set; }
        public float Price { get; set; }
        public int Quantity { get; set; }
        public int Product_ID { get; set; }
        public int Bill_num { get; set; }
    }
}
