//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniMarket
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MinimarketEntities1 : DbContext
    {
        public MinimarketEntities1()
            : base("name=MinimarketEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<bill> bills { get; set; }
        public DbSet<employee> employees { get; set; }
        public DbSet<item> items { get; set; }
        public DbSet<port> ports { get; set; }
        public DbSet<product> products { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
