//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class port
    {
        public int Portselling_ID { get; set; }
        public string Portselling_name { get; set; }
        public string Product_category { get; set; }
        public string address { get; set; }
    }
}
