//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product1
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string ProductCateg { get; set; }
        public float ProductPrice { get; set; }
        public int ProductQty { get; set; }
        public System.DateTime Data_of_production { get; set; }
        public System.DateTime Data_of_expiration { get; set; }
        public string name_importer { get; set; }
        public int Buy_id { get; set; }
    }
}
