//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int Product_ID { get; set; }
        public string Product_name { get; set; }
        public int Product_quantity { get; set; }
        public float Product_price { get; set; }
        public System.DateTime Dateofproduction { get; set; }
        public System.DateTime Dateofexpiration { get; set; }
        public int Portselling_ID { get; set; }
        public int item_id { get; set; }
    }
}
